name: Bug report
description: Zgłoś błąd w gamemodzie
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Wypełnij formularz jak najdokładniej. Dzięki temu łatwiej odtworzymy i naprawimy problem.

  - type: textarea
    id: description
    attributes:
      label: Opis błędu
      description: Co się dzieje? Co powinno się dziać?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Kroki do odtworzenia
      placeholder: |
        1. Wejdź do...
        2. Użyj komendy...
        3. Widzisz błąd...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Oczekiwane zachowanie
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Wersja gamemode'u
      placeholder: "np. v1.0.0 lub commit hash"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logi / błędy (jeśli są)
      render: shell
